name: Node.js CI

on:
  push:
    branches:
      - frontend-test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build with Maven
      - run: npm install && npm run build && npm test
  update-frontend-prod-branch:
    needs: test
    name: Merge frontend-test into frontend-prod after tests run successfully
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'frontend-test'
          target: 'frontend-prod'
