name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js '14'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
  update-frontend-prod-branch:
    needs: build
    name: Merge frontend-test into frontend-prod after tests run successfully
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'frontend-test'
          target: 'frontend-prod'
